// Generated by Wrangler on Wed Jun 12 2024 19:17:52 GMT+0300 (Israel Daylight Time)
// by running `wrangler types`

interface Env {
	STORAGE: KVNamespace;
	BOT_INFO: string;
	TELEGRAM_BOT_TOKEN: string;
}
