#:schema node_modules/wrangler/config-schema.json
name = "afm-tickets-webhook"
main = "src/index.ts"
compatibility_date = "2024-06-10"
compatibility_flags = ["nodejs_compat"]

[vars]
BOT_INFO = "{\"ok\":true,\"result\":{\"id\":7210640302,\"is_bot\":true,\"first_name\":\"Anne Frank Museum Tickets Bot\",\"username\":\"afm_tickets_bot\",\"can_join_groups\":true,\"can_read_all_group_messages\":false,\"supports_inline_queries\":false,\"can_connect_to_business\":false}"

[[kv_namespaces]]
binding = "STORAGE"
id = "1123730b393d43fba0a28d46fcf2ce17"